"""empty message

迁移 ID: cb7710591553
父迁移: 
创建时间: 2026-02-21 10:41:55.478491

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cb7710591553'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_qq', sa.String(length=64), nullable=False, comment='Bot QQ号'),
    sa.Column('admin_qq', sa.String(length=64), nullable=False, comment='管理员QQ号'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('bot_qq', 'admin_qq', name='uq_admin_bot_qq_admin_qq'),
    info={'bind_key': 'multi_echo'}
    )
    op.create_table('delays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_qq', sa.String(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delays')),
    info={'bind_key': 'multi_echo'}
    )
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delays_bot_qq'), ['bot_qq'], unique=True)

    op.create_table('follow_switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_follow_switches_ck_feature_switch_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_switches')),
    info={'bind_key': 'multi_echo'}
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_qq', sa.String(length=64), nullable=False, comment='Bot QQ号'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='商品代号'),
    sa.Column('max_price', sa.Integer(), nullable=False, comment='费用上限'),
    sa.Column('min_price', sa.Integer(), nullable=False, comment='费用下限'),
    sa.Column('is_onepack', sa.Boolean(), nullable=False, comment='是否一包杀'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods')),
    sa.UniqueConstraint('bot_qq', 'code', 'is_onepack', name='uq_goods_bot_qq_code_onepack'),
    info={'bind_key': 'multi_echo'}
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_qq', sa.String(length=64), nullable=False, comment='Bot QQ账号'),
    sa.Column('platform_id', sa.String(length=64), nullable=False, comment='QQ群号'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('bot_qq', 'platform_id', name='uq_group_bot_qq_platform_id'),
    info={'bind_key': 'multi_echo'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('goods')
    op.drop_table('follow_switches')
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delays_bot_qq'))

    op.drop_table('delays')
    op.drop_table('admins')
    # ### end Alembic commands ###
