"""empty message

迁移 ID: d73a8d53cc97
父迁移: cb7710591553
创建时间: 2026-02-21 18:39:37.996721

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd73a8d53cc97'
down_revision: str | Sequence[str] | None = 'cb7710591553'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_delays_bot_qq'))
        batch_op.create_index(batch_op.f('ix_delays_bot_qq'), ['bot_qq'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delays_bot_qq'))
        batch_op.create_index(batch_op.f('ix_delays_bot_qq'), ['bot_qq'], unique=1)
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
