"""empty message

迁移 ID: ead466170ef1
父迁移: d73a8d53cc97
创建时间: 2026-02-21 22:07:48.823014

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ead466170ef1'
down_revision: str | Sequence[str] | None = 'd73a8d53cc97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_qq', sa.String(length=64), nullable=False, comment='Bot QQ号'),
    sa.Column('user_qq', sa.String(length=64), nullable=False, comment='被屏蔽用户QQ号'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_users')),
    sa.UniqueConstraint('bot_qq', 'user_qq', name='uq_blocked_bot_qq_user_qq'),
    info={'bind_key': 'multi_echo'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
